# Generated by Django 4.2.2 on 2023-06-13 18:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_bloggroup_id_alter_comment_id_alter_image_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=blog.models.upload_to),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
