# Generated by Django 4.2.2 on 2023-06-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_images_post_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='type',
        ),
    ]
